name: CI/CD Pipeline com CodeQL
on: [push, pull_request]

jobs:

# JOB 1: Executa primeiro e verifica segurança
  codeql-analysis:
    name: "Análise CodeQL"
    runs-on: ubuntu-latest
    
 # JOB 2: Testes unitários (Só roda se Job 1 passar)
  tests:
    name: "Testes Automatizados"
    needs: codeql-analysis
    runs-on: ubuntu-latest
    
# JOB 3: Entrega contínua (Só roda se Job 1 e 2 passarem)
  deploy-stage:
    name: "Deploy para Stage"
    needs: [codeql-analysis, tests]
    environment: stage
    runs-on: ubuntu-latest
